### ISSUE TITLE
Failure to install on Mac OS X Sierra 10.12.2 (16C68)

### ISSUE THREAD

**Issue by rarnaout** [refresh-bio/FAMSA#1]
Usually there's a readme and an installation script; here there's just a makefile.

When I type

make

I get the following error:

$ make
g++ -Wall -O3 -m64 -std=c++11 -pthread -I libs -I libs-linux  -fopenmp -c famsa_cpu/famsa_cpu.cpp -o famsa_cpu/famsa_cpu.o
clang: error: unsupported option '-fopenmp'
make: *** [famsa_cpu/famsa_cpu.o] Error 1

It appears that OS X doesn't have native support for openmp.

I am relatively new to installations of this kind. If you have instructions for installation/use on Macintosh OS X, I would be very grateful---as I'm sure would many others.

Thanks,

Ramy

**Comment by agudys** [comment]
We removed OpenMP dependency in 1.2 version. The package should now properly compile on OS X (tested on 10.11). A precompiled binary for OS X is also available under Release tab. Please check, whether this solves your problem.
