### ISSUE TITLE
Cannot "make" on OSX 10.13.4

### ISSUE THREAD

**Issue by BrendanW-M** [refresh-bio/FAMSA#10]
Hi, i'm trying to "make" FAMSA but it keeps returning this error

Brendans-MacBook-Pro:FAMSA-1.2 brendan$ MAKE
g++ -Wall -O3 -m64 -std=c++11 -pthread -I libs -I libs-linux  -c famsa_cpu/famsa_cpu.cpp -o famsa_cpu/famsa_cpu.o
famsa_cpu/famsa_cpu.cpp:11:10: fatal error: string: No such file or directory
 #include <string>
          ^~~~~~~~
compilation terminated.
make: *** [famsa_cpu/famsa_cpu.o] Error 1
Brendans-MacBook-Pro:FAMSA-1.2 brendan$ 

I'm very new to this sort of stuff, any help would be appreciated, thanks!

**Comment by agudys** [comment]
Hi! I'll check this out and let you know.
Regards,
Adam

**Comment by BrendanW-M** [comment]
Hi Adam

Thanks for the lightning fast response. I'm very interested in FAMSA due to the iterative refinements it runs, and i'm working with quite large protein families so FAMSA would be advantageous!


Kind Regards

Brendan

On 2 Aug. 2018 6:58 pm, Adam Gudyś <notifications@github.com> wrote:

Hi! I'll check this out and let you know.
Regards,
Adam

**Comment by agudys** [comment]
Dear Brendan,

Sorry for the delay in response - I was on vacation. I was not able to reproduce the error on OS X 10.12 machine. I'll let you know when I get access to 10.13 system. In the meantime, you can check OS X binary that has been added to the latest release.

Adam

**Comment by BrendanW-M** [comment]
Hi Adam,


Thanks for getting back to me. When I download the .osx file my Macbook tells me I have no application to open it with? I have never come across a .osx file before and can't figure out what to do with it?



Kind Regards


Brendan

________________________________

**Comment by agudys** [comment]
Hi,
I guess execution permissions have disappeared while uploading the file on Github. Add permissions through GUI or from terminal (`chmod +x filename`).

**Comment by BrendanW-M** [comment]
It worked! Thanks Adam! :D



Kind Regards


Brendan

________________________________
