### ISSUE TITLE
How to install/compile on linux?

### ISSUE THREAD

**Issue by bioteksampath** [refresh-bio/FAMSA#12]
Hi...
Thanks for this program seems very worth to try.
I have problem with installation, could you plz suggest a better way to install? 

Here is what I did

git clone https://github.com/refresh-bio/FAMSA.git
cd FAMSA
make -C ~/bin/FAMSA/bin/

Error;
/usr/bin/ld: cannot find -lOpenCL
collect2: error: ld returned 1 exit status
make: *** [makefile:103: famsa-gpu] Error 1
make: Leaving directory '/home/AAFC-AAC/perumals/bin/FAMSA'

perhaps you may add installation instructions into the readme.txt file 
alternatively, you may deposit to conda ( which is very easy to install a program).

Thanks a lot!
Regards
sam

**Comment by agudys** [comment]
Hello Sam,

 It looks that your machine does have OpenCL installed (which is required is you want FAMSA to use GPU). Please modify NO_GPU switch at the top of the makefile. You can find more detailed intructions in README.MD file in the repository (it's the best to view [https://github.com/refresh-bio/FAMSA](https://github.com/refresh-bio/FAMSA) directly through browser).

Regards,
Adam

**Comment by agudys** [comment]
The latest FAMSA version does not support GPU. Thus, all GPU-related  problems should be gone.

Regards,
Adam
