### ISSUE TITLE
Failure of make

### ISSUE THREAD

**Issue by THinnerichs** [refresh-bio/FAMSA#13]
Hey there,
When running ```make``` on the freshly cloned repo, it eventually throws
```
core/msa.o: In function `CFAMSA::ExportDistanceMatrix(float*, unsigned long, std::string const&)':
msa.cpp:(.text+0x31da): undefined reference to `CFAMSA::UPGMA_TriangleSubscript(unsigned long, unsigned long)'
collect2: error: ld returned 1 exit status
```
which seems like there are some classes missing.

**Comment by agudys** [comment]
Hello,
It seems that I've accidentally broken Linux compilation in the last update. I'll take a look on that ASAP. In the meantime please use the previous version (it lacks only export of the distance matrix).

Regards,
Adam

**Comment by THinnerichs** [comment]
Thanks for the quick response! I finally got your precompiled binaries to run after some issues with ```glib``` and ```libgcc```, so its not quite urgent.
Cheers,
Tilman

**Comment by agudys** [comment]
Hi,
I'm glad you've managed to run it. In the meantime I fixed the bug - it should compile correctly now.
Regards,
Adam

**Comment by THinnerichs** [comment]
Thank you :)
