### ISSUE TITLE
Version 1.3.2: precompiled binaries for osx / compile on MacOS?

### ISSUE THREAD

**Issue by JiaminShi** [refresh-bio/FAMSA#16]
I am trying to compile 1.3.2 on Mac Mojave 10.14.6 but got
```
$make
g++ -Wall -O3 -m64 -std=c++11 -pthread -I libs -I libs-linux -mavx  -mpopcnt -funroll-loops -c core/lcsbp_avx.cpp -o core/lcsbp_avx.o
g++ -Wall -O3 -m64 -std=c++11 -pthread -I libs -I libs-linux -mavx2  -mpopcnt -funroll-loops -c core/lcsbp_avx2.cpp -o core/lcsbp_avx2.o
g++ -lm -O3 -std=c++11 -pthread  -o famsa famsa_cpu/famsa_cpu.o core/input_file.o core/msa.o core/output_file.o core/profile.o core/sequence.o core/queues.o core/timer.o core/upgma.o core/NewickTree.o libs/instrset_detect.o opencl_utils/common/Log.o opencl_utils/common/mathex.o opencl_utils/common/StatisticsProvider.o  core/lcsbp.o core/lcsbp_classic.o core/lcsbp_avx.o core/lcsbp_avx2.o libs-linux/libamac64.a
make: *** No rule to make target `famsa-gpu', needed by `all'.  Stop.
```

Could you please indicate what I should do with it? thanks a lot!

**Comment by agudys** [comment]
Hello,
By default GPU binary is not built under MacOS. The message you mentioned should not be a problem, since you should have CPU binary named `famsa` created. If not, please remove `famsa-gpu` entry from the first line of the makefile.
Adam

**Comment by agudys** [comment]
Hi,
Alternatively, you can switch to `experimental` branch with the latest FAMSA version. In this version GPU support has been removed, thus you should compile successfully under MacOS.
Adam

**Comment by agudys** [comment]
Current version of FAMSA compiles on macOS. Pre-built binaries have been also added.
