### ISSUE TITLE
Trouble installing FAMSA

### ISSUE THREAD

**Issue by 000generic** [refresh-bio/FAMSA#18]
On a Linux Debian 9 system I ran 

**git clone https://github.com/refresh-bio/FAMSA.git**

and then entered the FAMSA directory and ran

**make**

and then see

**famsa  FAMSA.sln  libs	libs-linux  libs-win  makefile	README.md  src**

but when I try to run famsa from this directory I get

**famsa
-bash: famsa: command not found**

I apologize if this is very basic but what am I missing on installation of famsa.

Thank you!

**Comment by agudys** [comment]
Hello,

From the terminal you should rather run `./famsa`. Please tell me if it helps.

Regards,
Adam

**Comment by 000generic** [comment]
Works awesome!  Sorry - such a simple thing but I was stuck :)

**Comment by agudys** [comment]
No problem, I'm closing the issue then.
