### ISSUE TITLE
make fails on Linux - 'align' was not declared in this scope

### ISSUE THREAD

**Issue by dmgood11** [refresh-bio/FAMSA#2]
Attempting to build  FAMSA executable  using g++ version 4.8 on a Linux box

$ g++ --version
g++ (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ uname -a
Linux gpint202 2.6.32-431.46.2.el6.nersc.x86_64 #1 SMP Thu Jan 22 09:48:18 PST 2015 x86_64 GNU/Linux
$ make 2>&1 | tee make.output.txt
[make.output.txt](https://github.com/refresh-bio/FAMSA/files/728083/make.output.txt)

make command eventually fails with:

g++ -Wall -O3 -m64 -std=c++11 -pthread -I libs -I libs-linux  -fopenmp  -mavx -fabi-version=0 -mpopcnt -funroll-loops -c core/lcsbp_avx.cpp -o core/lcsbp_avx.o
core/lcsbp_avx.cpp: In member function 'void CLCSBP_AVX::prepare_X(size_t)':
core/lcsbp_avx.cpp:35:51: error: 'align' was not declared in this scope
  X = (Vec2uq*) align(64, X_size, raw_X, raw_X_size);

Also failed with other g++ versions from 4.6.3 to 6.3.0

Complete output of make command is attached.

**Comment by agudys** [comment]
This error is caused by g++ 4 not implementing std::align function. However, FAMSA should build properly with g++ 5 (tested both g++5.3 and 5.4). Are you sure you changed default g++ version after the update?

**Comment by agudys** [comment]
std::align dependency has been removed in the latest (1.2.1) release, thus you should be able to compile it successfully using g++4.8.
