### ISSUE TITLE
FAMSA hangs on identical sequences

### ISSUE THREAD

**Issue by arvestad** [refresh-bio/FAMSA#34]
FAMSA (version 2.1.2- (2022-08-04) installed using conda) hangs without progress if I run it on a set of identical sequences (but different accessions). Editing a single sequence to a different residue will make FAMSA to behave as intended. Using the option --keep-duplicates is also a work-around.

**Comment by agudys** [comment]
Hello @arvestad, 
Thank you for reporting the issue.  I'll do my best to fix it soon!
Regards,
Adam

**Comment by agudys** [comment]
Hello @arvestad!

The bug has hopefully been fixed in the latest commit. Please let me know if it works (you would need to build the binary from the sources, though - it is not on bioconda yet).

Best,
Adam

**Comment by arvestad** [comment]
Thanks, I cannot prioritize this for a few days unfortunately.
