### ISSUE TITLE
Famsa gets stuck

### ISSUE THREAD

**Issue by bioinsilico** [refresh-bio/FAMSA#41]
Hi, Famsa devels!

I am using v2.1.2, and it seems to get stuck in a dummy case. The program is frozen, and no output is generated.
`app/famsa/famsa-macos -t 1 ./tmp/align.fasta STDOUT`

`align.fasta` content

```
>3EMW_2
DINNNNNIVEDVERKREFYI
>3F2O_2
DINNNNNIVEDVERKREFYI
>2IHS_2
DINNNNNIVEDVERKREFYI
```

**Comment by agudys** [comment]
Hello! 

Sorry for responding for such a long time. The issue has been fixed in 2.1.3 version (not a release, though) so please try the latest 2.2.2 release.

Best,
Adam
