### ISSUE TITLE
Git submodules for vendored libraries

### ISSUE THREAD

**Issue by nathanweeks** [refresh-bio/FAMSA#45]
For the vendored libraries in libs/, has the use of [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) been considered for providing an easy mechanism to update dependencies to newer versions & preserve source code provenance?

Public git repositories exist for each project:

* https://github.com/microsoft/mimalloc
* https://github.com/ogiroux/atomic_wait
  * I assume this bundled until the relevant C++20 interfaces are broadly available in supported compilers?
* https://github.com/ebiggers/libdeflate

**Comment by agudys** [comment]
Hello!
Indeed, we are planning to include these dependencies as submodules. We will schadule it for the next release.

Best,
Adam

**Comment by agudys** [comment]
Hello @nathanweeks 

In the latest revision (2.2.3) all the dependencies has been now included as submodules.

Best,
Adam

**Comment by nathanweeks** [comment]
Confirmed everything still builds in my environment. Thanks!
