### ISSUE TITLE
Reading from STDIN, reporting to STDOUT

### ISSUE THREAD

**Issue by meren** [refresh-bio/FAMSA#5]
The only thing that prevents us to only rely on FAMSA at this point is the lack of a simple functionality: If FAMSA could work with standard input and output as an alternative to input and output files, it would have been excellent.

Thanks!

**Comment by agudys** [comment]
Hello,
Actually, FAMSA has the ability to use standard input and output. You just need to specify STDIN (STDOUT) as the name of the input (output) file. It may not be intuitive, but it should work. Please let me know.

**Comment by meren** [comment]
Holy crap. It is even in the help menu. I can't believe I missed that although I've been playing with it for awhile.

I will definitely be much less upset when my users ask me about things that are clearly explained in the help menu output.

I apologize for taking your time, and thank you very much. It of course worked like a charm :)

**Comment by agudys** [comment]
No problem, I am glad it worked :) If you have any problems or suggestions, please let us know.
