### ISSUE TITLE
Instructions for installation

### ISSUE THREAD

**Issue by ekiefl** [refresh-bio/FAMSA#6]
I am on mac 10.12.5. I cloned the repo and did `make`. The last two lines were

```
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
make: *** No rule to make target `famsa-gpu', needed by `all'.  Stop.
```

The next thing I tried was the latest release. I downloaded the release file but I don't know what to do with it. Here's what I tried:

![image](https://user-images.githubusercontent.com/8688665/32906764-8daa5820-cac3-11e7-95fa-7717dd8c4689.png)

Please advise. Thanks!

**Comment by agudys** [comment]
Hi! Sorry for the late response - i'll take a look on that.

**Comment by ppflrs** [comment]
In case anyone encounters the same problem using the 1.2.1 OS X release, you need to change the permissions to make it executable.

1. `cd` to the location where `famsa-1.2.1-osx` was downloaded
2. Give execution permissions by: `chmod +x famsa-1.2.1-osx`
3. Now you can execute famsa: `./famsa-1.2.1-osx`

**Comment by ekiefl** [comment]
I found the same solution @ppflrs. I was able to get things to work with the following commands:

```
wget https://github.com/refresh-bio/FAMSA/releases/download/v1.2.1/famsa-1.2.1-osx -O famsa
chmod +x famsa
sudo mv famsa /usr/local/bin/famsa
```

taken from [here](http://merenlab.org/2016/06/18/installing-third-party-software/#famsa)

**Comment by agudys** [comment]
Thank you @ppflrs and @ekiefl for resolving the issue on your own. Sorry for the delay - I've been kind of busy recently. In case of other problems, do not hesitate to contact me - I'll respond faster.
