### ISSUE TITLE
segmentation fault using gpu version

### ISSUE THREAD

**Issue by ivokwee** [refresh-bio/FAMSA#8]
Hi. 

I am getting a segfault using the gpu version. Both in the downloaded binary but also when compiling myself. Is setting device=0 and platform=0 correct? I tried also setting to 1 but same error. CPU version works fine.

Ivo

```
famsa-gpu -gpu_d 0 -gpu_p 0 input.fa out.fa 
FAMSA (Fast and Accurate Multiple Sequence Alignment) ver. 1.2.2 CPU and GPU
  by S. Deorowicz, A. Debudaj-Grabysz, A. Gudys (2018-03-20)

Getting OpenCL devices...
Segmentation fault (core dumped)
```

**Comment by agudys** [comment]
Hello Ivo,

You need to specify correct OpenCL platform and device identifier. For convenience, I will add to FAMSA a functionality to provide user with available platforms and devices. In the meantime, you can run our other GPU-suited software [QuickProbs](https://github.com/refresh-bio/QuickProbs/). When executed without parameters, it lists OpenCL configuration. Please let me know if it works.

Adam

**Comment by ivokwee** [comment]
Hi Adam. Thanks. I would have thought 0/0 would be the first (and only) gpu... I tried many other combinations without luck. How is QuickProbs different or better than FAMSA? Which do you recommend for multiple alignment of 100'000 short sequences of 500nt, or 150aa?

**Comment by agudys** [comment]
If you have 100k sequences, FAMSA is the choice - QuickProbs is more accurate, but won't handle such large sets. However, have you tried running QuickProbs CL executable without parameters to list available devices? Please provide me more details about your hardware configuration.

**Comment by agudys** [comment]
Hi Ivo. I've added a small fix to GPU binary which lists available OpenCL devices when executed without parameters. If you still obtain segfault, this may be related to some driver issues. I would need more information about your hardware and OS to find the solution.

**Comment by ivokwee** [comment]
Hi. 
Thanks. But I still cannot get FAMSA-gpu running. My system is the latest Ubuntu 18.04, g++ version 7.3.0, using an NVIDIA GeFoce 940MX, CUDA 9.0, nvidia-390. When I compile quickprobs and run quickprobs without anything, I get  
```
../quickprobs-cl-2.06-linux 
[...]
Following OpenCL devices have been found:
Platform 0: NVIDIA CUDA (OpenCL 1.2 CUDA 9.1.84)
	Device 0: GeForce 940MX
```

For FAMSA (your new code):
```
 ./famsa-gpu
[...]
Available OpenCL devices:
Segmentation fault (core dumped)
```

**Comment by jesalo** [comment]
Hi Adam,

I am getting the exact same error as Ivo. 

```
./famsa-gpu
Available OpenCL devices:
Segmentation fault (core dumped)
```
Ubuntu 16.04, Quadro K6000 GPU. Had same issue on Ubuntu 14.04 with Nvidia 1080Ti.

QuickProbs works fine:
```
Following OpenCL devices have been found:
Platform 0: NVIDIA CUDA (OpenCL 1.2 CUDA 9.0.368)
        Device 0: Quadro K6000
```

Thanks!

Jesper

**Comment by agudys** [comment]
It seems there's a problem with statically linked OpenCL library. I'll take a closer look on that an let you know.

**Comment by agudys** [comment]
Hello Ivo and Jesper,
I modified the makefile in the way that FAMSA is now linked against OpenCL library installed in the system (I also removed corresponding lib file from the repository). This should solve your problem. Please, rebuild and let me know.
Adam

**Comment by ivokwee** [comment]
works! thanks!

**Comment by agudys** [comment]
I am closing the issue then.

**Comment by jesalo** [comment]
Thank you Adam! I am away, but looking forward to test it when I return. 

Thanks for fixing it,

Jesper
