### ISSUE TITLE
Availability via conda

### ISSUE THREAD

**Issue by jacodela** [refresh-bio/FAMSA#9]
`famsa` is used by `anvio`, [an analysis and visualization suite for metagenomics](http://merenlab.org/software/anvio/), but as far as I can tell, `famsa` isn't available from conda, which difficults the package's installation and management. Are you planning (or currently working on) submitting `famsa` to Conda?

**Comment by agudys** [comment]
Hello,
Actually, we haven't thought about submitting FAMSA to Conda. Do you think it's worth the effort to do so? I always thought Conda was mainly for Python packages.

**Comment by jacodela** [comment]
Thanks for your answer! I'm mainly interested in a conda submission because my research group uses conda for installing and managing (almost) all of our bioinformatics software, which is not limited to python packages, but also includes unix-based software (e.g [seqtk](https://anaconda.org/bioconda/seqtk)) and R packages (e.g [Phyloseq](https://anaconda.org/bioconda/bioconductor-phyloseq)). In addition, submitting it to conda can help users actually use `famsa` in a reproducible software environment and to easily integrate it to analysis pipelines.

**Comment by agudys** [comment]
Then I guess we need to take a closer look on that and try to submit the software to Conda. I'll let you know!

**Comment by milot-mirdita** [comment]
I took the liberty of packaging famsa in conda (https://github.com/bioconda/bioconda-recipes/pull/19529), since we want to use in a pipeline. I hope that's okay. Could you take a look?

**Comment by agudys** [comment]
@milot-mirdita 
Sorry for not responding you earlier. Thank you very much for your time and effort to integrate FAMSA in bioconda! We really appreciate!
